### ISSUE TITLE
Upgrade React Native from 0.62.2 to 0.70.1

### ISSUE THREAD

**Issue by its-edmund** [GTBitsOfGood/brain-exercise#121]
React Native needs to be upgrade before we can use Expo Go for development. You can use this website as a guide: https://react-native-community.github.io/upgrade-helper/?from=0.62.2&to=0.70.1

Main Upgrades:
- [ ] React Native
- [ ] React
- [ ] ReactDOM

**Comment by XenonMolecule** [comment]
Although I didn't take it all the way to 0.70.1 I think #133 might've made some progress on this front
