### ISSUE TITLE
Adding user context to access user data

### ISSUE THREAD

**Issue by its-edmund** [GTBitsOfGood/brain-exercise#147]
In order to access the user object, we need to add some form of state management. Since it should be pretty simple, we can just use React Context. Documentation here: https://reactjs.org/docs/context.html

These are the following attributes that need to be in the context:
- TBD

**Comment by aidengibbs** [comment]
@therealsharath

**Comment by therealsharath** [comment]
@its-edmund any updates on which attributes need to be stored in context?

**Comment by its-edmund** [comment]
For now, I think it should be email, loggedIn, username?

**Comment by therealsharath** [comment]
Sounds good, ty!

**Comment by XenonMolecule** [comment]
@therealsharath you may find the framework I've setup with react redux useful if you haven't already gotten started with another approach: https://github.com/GTBitsOfGood/brain-exercise/blob/develop/src/components/Auth/LoginButton.tsx#L82

You can see how user state was persisted in the umifeeds app (very similar codebase) here: https://github.com/GTBitsOfGood/umi-feeds-app/blob/develop/redux/reducers/authReducer/index.ts

**Comment by therealsharath** [comment]
I saw that redux was setup in the App,js file and was wondering if I could just use redux to manage app wide context. Thanks for linking this, it'll help maintain consistency across the repo :)

**Comment by its-edmund** [comment]
Yeah, that should be fine
