### ISSUE TITLE
[Ticket][PMT] BEI Testing

### ISSUE THREAD

**Issue by jaynagpaul** [GTBitsOfGood/brain-exercise#172]
**Non-Profit Description**
Brain Exercise Initiative (BEI) is a nonprofit focused on preventing memory loss through brain exercise. Its founder is UCLA student Esin Gumustekin, who draws inspiration from the research work done by Dr. Ryuta Kawashima. Gumestekin creates daily packets which include simple math, writing and "read-alouds" that are completed by each individual with the guidance of university students. Several retirement homes have integrated her program into their center and chapters are currently being founded at different universities.

**Ticket Description**

**This ticket will be focused on testing the BEI application.**

This semester we made a few fixes/additions to BEI and we'd like to ensure we didn't break anything in the process.

This ticket will be a combination of investigating and bug fixing (if possible). We want to either independently or together try **to break the app as much as possible**. Please document any bugs however minor, and if you have time please fix them (not required, though would be much appreciated).

**Acceptance Criteria**
- [x] Thoroughly test the BEI mobile application and document issues. The issues that are documented show be done in the comments below this issue (and pictures would be helpful).
- [ ] **BONUS:** Fix the issues documented

**Notes**
* Please look at the Setup section in the ReadMe to understand how to work on the project
* Contact leadership if you need credentials!

**Comment by tsun900** [comment]
Android error appeard when open the app:
<img width="190" alt="image" src="https://user-images.githubusercontent.com/52758623/223017049-f77110a9-51f7-4418-b729-ee11b7909477.png">
<img width="767" alt="image" src="https://user-images.githubusercontent.com/52758623/223017268-784032f0-ad31-4bc1-b174-5ff001e62e4d.png">

**Comment by tsun900** [comment]
Android: Error appears when starting the game:
<img width="184" alt="image" src="https://user-images.githubusercontent.com/52758623/223017173-653da06e-078b-403a-9b06-5473ce4f6568.png">
<img width="936" alt="image" src="https://user-images.githubusercontent.com/52758623/223017232-c0f53a55-fd03-4c91-8275-2f98c5b5ae35.png">

**Comment by tsun900** [comment]
Android: The shade of button extends to both corner at top of button:
<img width="64" alt="image" src="https://user-images.githubusercontent.com/52758623/223017381-94469f35-592b-44ee-908c-001d2b9fbd66.png">

**Comment by tsun900** [comment]
Android: Error appears when clicked quit button on pause page:
<img width="193" alt="image" src="https://user-images.githubusercontent.com/52758623/223017550-76edee87-783e-48ad-afd9-bc85ae937dcc.png">
<img width="824" alt="image" src="https://user-images.githubusercontent.com/52758623/223017567-fce09e6e-f870-43b4-a5b3-d40deddd1198.png">

**Comment by tsun900** [comment]
Android: When click continue to log in button, nothing happened, following is the terminal message:
<img width="183" alt="image" src="https://user-images.githubusercontent.com/52758623/223018679-a8e613a5-8e4c-4984-aef5-8e31ce1df2d4.png">

**Comment by tsun900** [comment]
Android: Error appears when change sound setting:
<img width="187" alt="image" src="https://user-images.githubusercontent.com/52758623/223018769-c842bc01-be24-43aa-a5fa-d8d12c579475.png">
<img width="948" alt="image" src="https://user-images.githubusercontent.com/52758623/223018818-792838e3-19ae-4a58-97f2-b468c6738219.png">

**Comment by tsun900** [comment]
When clicked on save inside the settings pages, the app returns to the main page instead of setting menu as one would expect

**Comment by tsun900** [comment]
Android: In writing section, after click show answer, the 'next' and 'skip' button both lead to next question, it appears 'skip' button is redundant in this situation
<img width="189" alt="image" src="https://user-images.githubusercontent.com/52758623/223020104-1600da07-4156-42e0-911f-a17498f08b73.png">

**Comment by tsun900** [comment]
Android: When timer is up for writing section, it have a 'skip' button which seems strange
<img width="169" alt="image" src="https://user-images.githubusercontent.com/52758623/223020249-f77b6c5f-5795-4114-8f74-711d19c40f81.png">

**Comment by tsun900** [comment]
Android: in reading section, both next and skip button lead to next question without any difference:
<img width="175" alt="image" src="https://user-images.githubusercontent.com/52758623/223020380-fc2b5d0b-818f-440d-ac07-0e3f94477b8f.png">

**Comment by tsun900** [comment]
The reading passages seems incomplete, especially at begining some passages seems to start at middle of a sentence:
<img width="179" alt="image" src="https://user-images.githubusercontent.com/52758623/223021429-5d9a6c4e-8bda-4142-a2d1-62416a0e17bc.png">

**Comment by tsun900** [comment]
After click skip in math section, there are two seconds of freeze in the screen allow the user to read the answer, however, the timer did not pause, hence those two seconds are 'wasted'
<img width="176" alt="image" src="https://user-images.githubusercontent.com/52758623/223021588-2abd7104-f7c0-4db5-9d19-872da5d599d1.png">

**Comment by tsun900** [comment]
Continued notice of unhandled promise in android, I'm not sure as to the cause, the terminal give no information:
<img width="188" alt="image" src="https://user-images.githubusercontent.com/52758623/223021675-717709fe-5a62-45e6-9854-4630594adb47.png">

**Comment by tsun900** [comment]
Android: Writing prompt have similar problem as to reading section, two button have same feature

**Comment by tsun900** [comment]
There is no explanations regarding the score of exercises, in the same time some section are impossible to score
<img width="168" alt="image" src="https://user-images.githubusercontent.com/52758623/223023000-2aa46a63-1d6b-4c2d-b714-f744156520b1.png">

**Comment by tsun900** [comment]
Android: After I completed a brain exercise the home page still shows 0/5 days completed:
<img width="177" alt="image" src="https://user-images.githubusercontent.com/52758623/223023124-f070e5a4-7f54-48d7-87bb-696c193e1ceb.png">
