### ISSUE TITLE
Math Dynamic Difficulty

### ISSUE THREAD

**Issue by shopaniuk** [GTBitsOfGood/brain-exercise#43]
We currently have the ability to generate questions based on difficulty level, however, we currently are randomly choosing the difficulty level. 
We want users to have a personal “difficulty score” that persists in local async storage and gets adjusted based on correctness and time it takes per problem. This difficulty score will be a number between 100-499. Difficulty level 100-199 will get mapped to difficulty 1, 200-299 will get mapped to 2, etc.

**Comment by DeveloperKhan** [comment]
this is already done
