### ISSUE TITLE
[Android] Add user confirmation when navigating away (back navigation) from game screens

### ISSUE THREAD

**Issue by Arthelon** [GTBitsOfGood/brain-exercise#56]
When a User is in a game and they back navigate or modify the navigation stack, they should receive a confirm prompt before exiting.

**Comment by jlatour3** [comment]
Why is there a back button other than the first screen entering the game? Screens should be automatically flowing for the user with no option to go back, because timer restarts.

**Comment by Arthelon** [comment]
There is no UI back button. Android has a native back button for back navigation.

**Comment by shopaniuk** [comment]
This should be resolved now on develop but I haven't tested it on Android @Arthelon

**Comment by shopaniuk** [comment]
Instead of adding a user confirmation to go back I just removed the go back functionality for the game screens.
