### ISSUE TITLE
[iOS, All Screens] Disabling page turn shortcut 

### ISSUE THREAD

**Issue by jlatour3** [GTBitsOfGood/brain-exercise#60]
When the slider is all the way to the left, I can't use the slider. Instead it thinks I want to go back to the previous screen, is there a way to disable this?

**Comment by jlatour3** [comment]
This is particularly noticeable when a user is trying to change text size but you can go back to the previous screen by sliding right.

**Comment by shopaniuk** [comment]
Now fixed, I disabled gestures on the Font Slider screen.

**Comment by jlatour3** [comment]
I can still swipe back on the gameplay screens, is there a way to disable all of those screens as well? I can swipe back on the writing intro screen after completing 5 minutes of math and it takes me back to beginning of math, where I have to wait five minutes or do math problems again.

**Comment by shopaniuk** [comment]
Gestures are now disabled on all screens. I don't think we'll need them for any of our screens regardless of text size
