### ISSUE TITLE
Writing prompts not added to PromptScreen.jsx

### ISSUE THREAD

**Issue by jlatour3** [GTBitsOfGood/brain-exercise#62]
Short prompts of writing section is not implemented, empty `PromptScreen.jsx` screen.

**Comment by jlatour3** [comment]
Looks like Matt and Jack's PR got overridden my Game flow task:
Matt + Jack : https://github.com/GTBitsOfGood/brain-exercise/pull/48/files
Gameflow: https://github.com/GTBitsOfGood/brain-exercise/pull/50/files
If you look at the `PromptScreen.jsx` file in these PRs, then you'll see that the implementation is there, it's just that they got kicked off of the main branch when the second PR is merged.

**Comment by shopaniuk** [comment]
Fixed and merged in
