### ISSUE TITLE
[UI] Settings screens looks strange

### ISSUE THREAD

**Issue by jlatour3** [GTBitsOfGood/brain-exercise#65]
Notifications, Font Size, Sounds, Animation are the main settings to change but as the font size increases, it is harder to differentiate between Notifications and the two sub-options "Daily Reminder" and "Set Reminder Time" . Is there any way we can differentiate the Notifications, Font Size, Sounds, Animation more clearly?

**Comment by shopaniuk** [comment]
How would you like them to be differentiated? @jlatour3

**Comment by jlatour3** [comment]
Designers made the differentiation with icons and dividers. At a minimum, I think dividing the settings would help, if not the icons as well. I don't know React's icon library well, but I believe our designers used icons from there. @shopaniuk 
![image](https://user-images.githubusercontent.com/46651129/91455372-fc3ae500-e84f-11ea-9f2d-84cb955c709b.png)

**Comment by jlatour3** [comment]
My only concern with icons would be, would they dynamically change with text? When you change iPhone's text size, the icons will stay the same size and vertically center themselves with the adjusted text size. This is what I would prefer.

**Comment by shopaniuk** [comment]
Okay can do!
