### ISSUE TITLE
[UI, Writing Game, Android] Text content does not overflow vertically

### ISSUE THREAD

**Issue by Arthelon** [GTBitsOfGood/brain-exercise#68]
When the question and answer text are above the container height, they overflow horizontally instead of vertically.

![image](https://user-images.githubusercontent.com/11952174/91187505-3e342180-e6be-11ea-947d-2a14cf237aaa.png)

**Comment by DeveloperKhan** [comment]
![Simulator Screen Shot - iPhone SE (2nd generation) - 2020-09-01 at 16 14 11](https://user-images.githubusercontent.com/26877561/91901454-39e3a780-ec6e-11ea-9b55-e5ae98530ba9.png)
![Simulator Screen Shot - iPhone SE (2nd generation) - 2020-09-01 at 16 14 13](https://user-images.githubusercontent.com/26877561/91901455-39e3a780-ec6e-11ea-9e03-9c6c02da10e2.png)

My solution is removing the instructions after they are not relevant (when the answer shows)
