### ISSUE TITLE
[UI, Math, iOS/Android] Math choices overflow boxes

### ISSUE THREAD

**Issue by jlatour3** [GTBitsOfGood/brain-exercise#74]
Math choices don't fit the boxed selections when the text font is set to higher font sizes

![image](https://user-images.githubusercontent.com/46651129/91343630-d4457600-e7aa-11ea-8c1b-b4d07db3b256.png)

**Comment by Fattimo** [comment]
![image](https://user-images.githubusercontent.com/57023314/91379408-a08d3f00-e7f0-11ea-81da-67b0da714b83.png)

**Comment by shopaniuk** [comment]
So for this there are two options. Either the blue Answer Buttons can scale larger in size as well or the text in the buttons can have a font size maximum that is lower than the font slider maximum. Which would you prefer? @jlatour3

**Comment by jlatour3** [comment]
@shopaniuk, set the font size of the text in the buttons as a maximum please.

**Comment by DeveloperKhan** [comment]
![Simulator Screen Shot - iPhone SE (2nd generation) - 2020-09-01 at 15 49 57](https://user-images.githubusercontent.com/26877561/91899276-e7ed5280-ec6a-11ea-8d1f-6bddf13dc45c.png)
Here's my solution
