### ISSUE TITLE
[UI, Home Screen, iOS and Android] Inconsistent Home header

### ISSUE THREAD

**Issue by jlatour3** [GTBitsOfGood/brain-exercise#84]
Confusing header between "0 of 5 Days" and "1 of 5 days". I am not sure how the counter works for each. Either display no header or the day of the week (e.g. Monday)
![image](https://user-images.githubusercontent.com/46651129/91383249-ae938d80-e7f9-11ea-83bd-09f706aa7dfc.png)

**Comment by shopaniuk** [comment]
I removed the header title (the "1 of 5 Days") and kept the "X of 5 Days" one.
