### ISSUE TITLE
[UI, All Screens, iOS] Disable dynamic type on BEI application

### ISSUE THREAD

**Issue by jlatour3** [GTBitsOfGood/brain-exercise#85]
![image](https://user-images.githubusercontent.com/46651129/91456624-7e77d900-e851-11ea-8796-ef42768670e3.png)

Most seniors will most likely have larger text enabled on their iPhone, and if our app supports Apple's Dynamic Type in addition to our own accessibility feature, then it will increase our font size way too much like the picture. This is max size of the BEI app + max size of Text Size in iOS.

**Comment by jlatour3** [comment]
@Fattimo @Arthelon I would appreciate if y'all could figure out if the same happens on Android accessibility and what to disable if this happens.

**Comment by shopaniuk** [comment]
This is fixed on iOS now but I haven't verified on Android @Arthelon
