### ISSUE TITLE
Change writing (trivia) instructions

### ISSUE THREAD

**Issue by jlatour3** [GTBitsOfGood/brain-exercise#87]
The updated writing (trivia) instructions are quite long, especially with higher font sizes, it takes up a lot of the screen. Time permits, change to:
- [ ]  Writing (Trivia) screen saying "Grab some paper and a pencil and write what you see" 
- [ ] Boom squad can add the grab.mp3 for both screens so there are consistent voice instructions
- [ ] Add a simple screen following the Writing (Trivia) that says "Writing is a great way to exercise your brain so please write each trivia question first before answering."

**Comment by DeveloperKhan** [comment]
![Simulator Screen Shot - iPhone SE (2nd generation) - 2020-09-01 at 16 00 36](https://user-images.githubusercontent.com/26877561/91900187-4d8e0e80-ec6c-11ea-9432-4a173a46f62b.png)
My solution

**Comment by jlatour3** [comment]
I like it
